title: Imagine if you could learn from anyone on the planet.
author: Salim Virani
email: smile@saintsal.com
description: This is Salim Virani's blog.
permalink: /:title/

twitter_username: saintsal
github_username:  saintsal

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.html
 - http://source.institute

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
